main/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = "main"

urlpatterns = [
    path("", views.home, name="home"),
    path("post/<str:author>/<slug:slug>", views.detail, name="detail"),
    path("login", LoginView.as_view(template_name="main/login.html"), name="login"),
    path("register", views.register, name="register"),
    path("logout", LogoutView.as_view(template_name="main/logout.html"), name="logout"),
    path("new", views.add_post, name="new"),
    path("edit", views.edit, name="edit"),
    path("update", views.update, name="update"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("delete", views.delete, name="delete"),
    path("addcomment", views.add_comment, name="addcomment"),
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    re_path(r"^tinymce/", include("tinymce.urls")),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from tinymce.models import HTMLField
import readtime


class Post(models.Model):
    title = models.CharField(max_length=500)
    short_desc = models.CharField(max_length=500, default="no description")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = HTMLField()
    slug = models.SlugField(unique=True, max_length=100)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_readtime(self):
        return readtime.of_html(self.content)

    class Meta:
        ordering = ["-date_created"]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    content = models.CharField(max_length=1000)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ["-date_created"]

main/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "short_desc"]

main/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect


def home(request):
    posts = Post.objects.all()
    context = {"posts": posts}
    return render(request, "main/home.html", context)


def detail(request, author, slug):
    try:
        author = User.objects.get(username=author)
    except:
        author = None
    post = get_object_or_404(Post, slug=slug, author=author)
    comments = post.comments.all()
    context = {"post": post, "comments": comments}
    return render(request, "main/detail.html", context)


def register(request):
    context = {}
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.add_message(
                request,
                messages.SUCCESS,
                f"Succesfully registered {username}. You can now log in.",
            )
            return redirect("main:login")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "main/register.html", context)


@login_required
def add_post(request):
    if request.method == "GET":
        return render(request, "main/addpost.html", {"form": PostForm})
    else:
        user = User.objects.get_by_natural_key(request.user.username)
        form = PostForm(request.POST)
        if form.is_valid():
            Post.objects.create(
                author=user,
                title=form.cleaned_data["title"],
                content=form.cleaned_data["content"],
                short_desc=form.cleaned_data["short_desc"],
            )
            messages.add_message(
                request,
                messages.SUCCESS,
                "Post succesfully added",
            )
            return redirect("main:home")


@login_required
def edit(request):
    if request.method == "POST":
        user = User.objects.get_by_natural_key(request.user.username)
        id = request.POST.get("id")
        post = Post.objects.get(id=id)
        if post.author == user:
            return render(request, "main/editpost.html", {"post": post})


@login_required
def update(request):
    if request.method == "POST":
        user = User.objects.get_by_natural_key(request.user.username)
        id = request.POST.get("id")
        post = Post.objects.get(id=id)
        if post.author == user:
            post.title = request.POST.get("title")
            post.content = request.POST.get("content")
            post.short_desc = request.POST.get("short_desc")
            post.save()
    return redirect("main:dashboard")


@login_required
def dashboard(request):
    user = User.objects.get_by_natural_key(request.user.username)
    posts = Post.objects.filter(author=user)
    return render(request, "main/dashboard.html", {"posts": posts})


@login_required
def delete(request):
    if request.method == "POST":
        user = User.objects.get_by_natural_key(request.user.username)
        id = request.POST.get("id")
        post = Post.objects.get(id=id)
        if post.author == user:
            post.delete()

    return redirect("main:dashboard")


def add_comment(request):
    if request.method == "POST":
        id = request.POST.get("id")
        post = Post.objects.get(id=id)
        content = request.POST.get("content")
        Comment.objects.create(post=post, content=content)
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

main/templates/main/addpost.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% load static %}
<!---->
{% block meta %}
<title>Add New Post</title>
<script
  src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"
  referrerpolicy="origin"
></script>
<script>
  tinymce.init({ selector: "textarea" });
</script>
{% endblock meta %} {% block content %}
<div class="container py-5" style="max-width: 650px">
  {% include 'main/messages.html' %}
  <div class="row">
    <div class="col">
      <h3>Add new post</h3>
      <hr />
      <form method="post">
        {% csrf_token %} {{form|crispy}}
        <br />
        <button type="submit" class="btn btn-sm btn-primary">Add</button>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

main/templates/main/dashboard.html
{% extends 'base.html' %} {% load humanize %} {% load static %} {% block meta %}
<title>Blog App</title>
{% endblock meta %} {% block content %}
<div class="container py-5" style="max-width: 650px">
  <h1>My Posts</h1>
  {% for post in posts %}
  <div class="card my-3">
    <div class="card-body">
      <h2>{{ post.title }}</h2>
      <small> <i class="fas fa-user"></i> &nbsp; {{post.author}} </small>
      <br />
      <small>
        <i class="fas fa-calendar-day"></i> &nbsp;
        {{post.date_created|naturaltime}}
      </small>
      <br />
      <small><i class="fas fa-clock"></i> &nbsp; {{post.get_readtime}}</small>
      <hr />
      <p>{{post.short_desc}}</p>
      <a href="{% url 'main:detail' post.author post.slug %}">read more</a>
      <form action="{% url 'main:delete' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{post.id}}" />
        <input type="submit" value="delete post" />
      </form>
      <form action="{% url 'main:edit' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{post.id}}" />
        <input type="submit" value="edit post" />
      </form>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}

main/templates/main/detail.html
{% extends 'base.html' %} {% load humanize %} {% load static %} {% block meta %}
<title>Blog App</title>
{% endblock meta %} {% block content %}
<div class="container py-5" style="max-width: 650px">
  <h1>{{post.title}}</h1>
  <hr />
  <p>{{post.short_desc}}</p>
  <hr />

  <p>
    <i class="fas fa-user"></i> &nbsp; {{post.author}}
    <br />
    <i class="fas fa-calendar-day"></i> &nbsp; {{post.date_created}}
    <br />
    <i class="fas fa-clock"></i> &nbsp; {{post.get_readtime}}
  </p>
  <hr />
  <div>{{post.content|safe}}</div>
  <hr />
  <div>
    <h4>Comments</h4>
    <br />
    {% if comments %} {% for comment in post.comments.all %}
    <div class="card">
      <div class="card-body">
        <small>
          <i class="fas fa-clock"></i> &nbsp;
          {{comment.date_created|naturaltime}}
        </small>
        <hr />
        <p>{{comment.content}}</p>
      </div>
    </div>
    {% endfor %} {% else %}
    <p>no comments yet</p>
    {% endif %}
    <hr />
    <form action="{% url 'main:addcomment' %}" method="post">
      {% csrf_token %}
      <p>add new comment</p>
      <input type="text" name="content" id="comment_content" />
      <input type="hidden" name="id" value="{{post.id}}" />
      <input type="submit" value="Send" />
    </form>
  </div>
</div>

{% endblock content %}

main/templates/main/editpost.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% load static %}
<!---->
{% block meta %}
<title>Edit Post</title>
<script
  src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"
  referrerpolicy="origin"
></script>
<script>
  tinymce.init({ selector: "textarea" });
</script>
{% endblock meta %} {% block content %}
<div class="container py-5" style="max-width: 650px">
  {% include 'main/messages.html' %}
  <div class="row">
    <div class="col">
      <h3>Edit post</h3>
      <hr />
      <form method="post" action="{% url 'main:update' %}">
        {% csrf_token %}
        <div id="div_id_title" class="control-group">
          <label for="id_title" class="control-label requiredField">
            Title<span class="asteriskField">*</span>
          </label>
          <div class="controls">
            <input
              type="text"
              name="title"
              maxlength="500"
              class="textinput textInput"
              required=""
              id="id_title"
              value="{{post.title}}"
            />
          </div>
        </div>
        <div id="div_id_content" class="control-group">
          <label for="id_content" class="control-label requiredField">
            Title<span class="asteriskField">*</span>
          </label>
          <div class="controls">
            <textarea name="content" id="id_content" cols="30" rows="10">
              {{post.content}}
            </textarea>
          </div>
        </div>
        <div id="div_id_short_desc" class="control-group">
          <label for="id_short_desc" class="control-label requiredField">
            Short desc<span class="asteriskField">*</span>
          </label>
          <div class="controls">
            <input
              type="text"
              name="short_desc"
              value="{{post.short_desc}}"
              maxlength="500"
              class="textinput textInput"
              required=""
              id="id_short_desc"
            />
          </div>
        </div>
        <br />
        <input type="hidden" name="id" value="{{post.id}}" />
        <button type="submit" class="btn btn-sm btn-primary">Add</button>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %} {% load humanize %} {% load static %} {% block meta %}
<title>Blog App</title>
{% endblock meta %} {% block content %}
<div class="container py-5" style="max-width: 650px">
  <h1>Blog App</h1>
  {% include 'main/messages.html' %}
  <div>
    {% if user.is_authenticated %}
    <a href="/new">+ add new post</a>
    {% else %}
    <a href="/login">login</a> or <a href="/register">register</a> to add new
    post.
    <!---->
    {% endif %}
  </div>

  {% for post in posts %}
  <div class="card my-3">
    <div class="card-body">
      <h2>{{ post.title }}</h2>
      <small> <i class="fas fa-user"></i> &nbsp; {{post.author}} </small>
      <br />
      <small>
        <i class="fas fa-calendar-day"></i> &nbsp;
        {{post.date_created|naturaltime}}
      </small>
      <br />
      <small><i class="fas fa-clock"></i> &nbsp; {{post.get_readtime}}</small>
      <hr />
      <p>{{post.short_desc}}</p>
      <a href="{% url 'main:detail' post.slug %}">read more</a>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% load static %}
<!---->
{% block meta %}
<title>Blog App</title>
{% endblock meta %} {% block content %}
<div class="container py-5" style="max-width: 650px">
  {% include 'main/messages.html' %}
  <div class="row">
    <div class="col">
      <h3>Login</h3>
      <p>no account? <a href="/register">register</a></p>
      <hr />
      <form method="post">
        {% csrf_token %} {{form|crispy}}
        <br />
        <button type="submit" class="btn btn-sm btn-primary">Login</button>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

main/templates/main/logout.html
{% extends 'base.html' %} {% load static %} &nbsp; {% block meta %}
<title>Story 9</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'css/story9.css' %}" />
{% endblock meta %} {% block content %} {% include 'main/messages.html' %}
<div class="container">
  <div class="card p-4">
    <legend>You have successfully signed out</legend>
    <div class="card-footer text-center">
      <small><a href="{% url 'main:login' %}">Log in again?</a> </small>
    </div>
  </div>
</div>
{% endblock content %} {% block scripts %} {% endblock scripts %}

main/templates/main/messages.html
{% if messages %}
<ul class="messages container mt-4 mb-0" style="list-style: none">
  {% for message in messages %}
  <li class="alert alert-dismissible fade show">{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}

main/templates/main/register.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% load static %}
<!---->
{% block meta %}
<title>Blog App</title>
{% endblock meta %} {% block content %}
<div class="container py-5" style="max-width: 650px">
  {% include 'main/messages.html' %}
  <div class="row">
    <div class="col">
      <h3>Register</h3>
      <p>have an account already? <a href="/login">login</a></p>
      <hr />
      <form action="" method="POST">
        {% csrf_token %}
        <div>{{ form|crispy }}</div>
        <br />
        <button class="btn btn-primary" type="submit">Sign Up</button>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script
      src="https://kit.fontawesome.com/8a455c0870.js"
      crossorigin="anonymous"
    ></script>

    {% block meta %} {% endblock meta %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:home' %}">Home</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href={% url 'main:dashboard' %}>Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:new' %}">Add Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="/login">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/register">Register</a>
            </li>
            {% endif %}
          </ul>
          <form class="d-flex">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>
    {% block content %} {% endblock content %}
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
      crossorigin="anonymous"
    ></script>
  </body>
</html>